name: Publish
on:
    workflow_dispatch:
jobs:        
    publish:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run:  ls
            - name: install poetry
              run:  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
            - run:  poetry run pip install twine
            - run:  rm -fr dist/
            - run:  poetry build -f wheel
            - run:  poetry run twine upload -u __token__ -p ${{ secrets.PUBLISH_TOKEN }} dist/*whl
